del H:\알고리즘트레이딩2\buy_list.txt
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 0 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 100 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 200 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 300 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 400 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 500 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 600 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 700 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 800 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 900 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 1000 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 1100 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 1200 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 1300 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kospi 1400 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 0 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 100 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 200 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 300 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 400 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 500 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 600 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 700 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 800 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 900 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 1000 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 1100 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 1200 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 1300 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\PyGran.py kosdaq 1400 granville
C:\anaconda3_32\python C:\Users\user\Desktop\알고리즘트레이딩2\buySort.py